dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
     
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  sepolia:
    eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    host: http://127.0.0.1
    port: 8545
    gas_limit: 6721975
  ganache-local:
    verify: False
etherscan:
  token: ${ETHERSCAN_TOKEN}